# General data parameters
DATASET_PATH = 'dataset-resized'
SHUFFLE_DATA = True

# Data generator parameters
TRAINING_BATCH_SIZE = 16
TRAINING_IMAGE_SIZE = (28, 28)
VALIDATION_BATCH_SIZE = 16
VALIDATION_IMAGE_SIZE = (28, 28)
TESTING_BATCH_SIZE = 16
TESTING_IMAGE_SIZE = (28, 28)
NUMBER_OF_CHANNELS = 3